# Base configs
baseurl: "http://food.seonology.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-118569125-1"

# UI configs
title: "Photography by SEON"
subtitle: "I will only upload pictures of my food!"
author: "SEON NOH"
header:
 title: "Photography"
 subtitle: "by SEON"
footer:
 name: "Hello, i am SEON"
 bio: "I am a program engineer born in Korea.<br>
I live in Japan now.<br>
This site is just a site where I post pictures of my favorite foods. <br>
If you want to hear more stories, come <a href=\"https://github.com/ramswaroop/photography\">here</a> even though it is written in Korean."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/seon.noh.79"
  linkedin: "https://kr.linkedin.com/in/seontaek-noh-646b1054"
  github: "https://www.github.com/seonnoh"
